name: 'React Contentful Aws test | Deploy'

on:
  push:
    branches:
      - main
    paths:
      - '/**'

defaults:
  run:
    working-directory: /

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Build App'
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
        env:
          REACT_APP_CONTENTFUL_SPACE_ID: ${{ secrets.REACT_APP_CONTENTFUL_SPACE_ID }}
          REACT_APP_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.REACT_APP_CONTENTFUL_ACCESS_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets. AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets. AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Copy files to the s3 website content bucket
        run:
          aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest

      - name: Create invalidation for index.html
        run:
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/index.html"
